# Typical laptop setup, with wifi, brightness, battery etc, for

# For X11/i3, you'll want to replace calls to swaymsg with i3-msg, and
# the sway-xkb module with the xkb module.

# fonts we'll be re-using here and there
awesome: &awesome Font Awesome 6 Free:style=solid:pixelsize=14
awesome_brands: &awesome_brands Font Awesome 6 Brands:pixelsize=16
bg_default: &bg_default {stack: [{background: {color: 00000000}}, {underline: {size: 3, color: 98971aff}}]}
#bg_default: &bg_default {stack: [{background: {color: 81A1}}, {underline: {size: 4, color: D8DEE9ff}}]}
std_underline: &std_underline {underline: { size: 2, color: ff0000ff}}

# This is THE bar configuration
bar:
  height: 26
  location: top
  spacing: 5
  margin: 7

  # Default font
  font: Adobe Helvetica:pixelsize=14

  foreground: ffffffff
  background: 111111cc

  border:
    width: 1
    color: 999999cc
    margin: 5
    top-margin: 0

  left:
    - river:
        anchors:
          - base: &river_base
              left-margin: 10
              right-margin: 10 
              default: {string: {text: , font: *awesome}}
              conditions:
                id == 1: {string: {text: 1, font: *awesome}}  
                id == 2: {string: {text: 2, font: *awesome}}  
                id == 3: {string: {text: 3, font: *awesome}}  
                id == 4: {string: {text: 4, font: *awesome}}  
                id == 5: {string: {text: 5, font: *awesome}}  
                id == 6: {string: {text: 6, font: *awesome}}  
                id == 7: {string: {text: 7, font: *awesome}}  
                id == 8: {string: {text: 8, font: *awesome}}  
                id == 9: {string: {text: 9, font: *awesome}}
                # id == 21: {string: {text: "Scratchpad", font: *gomono}}

        content:
          map:
            on-click: 
              left: sh -c "riverctl set-focused-tags $((1 << ({id} - 1)))"
              right: sh -c "riverctl toggle-focused-tags $((1 << ({id} -1)))"
              middle: sh -c "riverctl toggle-view-tags $((1 << ({id} -1)))"
            conditions:
              state == urgent:
                map:
                  <<: *river_base
                  deco: {background: {color: D08770ff}}
              state == focused:
                map:
                  <<: *river_base
                  deco: *bg_default
              state == visible && ~occupied:
                map:
                  <<: *river_base
              state == visible && occupied:
                map:
                  <<: *river_base
                  deco: *bg_default
              state == unfocused:
                map:
                  <<: *river_base
              state == invisible && ~occupied: #{empty: {}}
                map:
                  <<: *river_base
                  #deco: *bg_default
              state == invisible && occupied:
                map:
                  <<: *river_base
                  deco: {underline: {size: 3, color: 00000000}}

  center:
    - clock:
        time-format: "%H:%M %Z"
        content:
          - string: {text: , font: *awesome, right-margin: 6}
          - string: {text: "{date}", right-margin: 5}
          - string: {text: , font: *awesome, right-margin: 8}
          - string: {text: "{time}"}

  right:

    - network:
        poll-interval: 1000
        content:
          map:
            default: {empty: {}}
            conditions:
              name == wlp3s0:
                map:
                  default: {string: {text: , font: *awesome, foreground: ffffff66}}
                  conditions:
                    state == down: {string: {text: , font: *awesome, foreground: ffffffff}}
                    state == up:
                      map:
                        default:
                          - string: {text: , font: *awesome}
                          - string: {text: "{ssid}", left-margin: 8}

                        conditions:
                          ipv4 == "":
                            - string: {text: , font: *awesome, foreground: ffffff66}
                            - string: {text: "{ssid}", left-margin: 8, foreground: ffffff66}

    - battery:
        name: BAT0
        poll-interval: 30000
        anchors:
          discharging: &discharging
            list:
              items:
                - ramp:
                    tag: capacity
                    items:
                      - string: {text:  , foreground: ff0000ff, font: *awesome}
                      - string: {text:  , foreground: ffa600ff, font: *awesome}
                      - string: {text:  , font: *awesome}
                      - string: {text:  , font: *awesome}
                      - string: {text:  , font: *awesome}
                      - string: {text:  , font: *awesome}
                      - string: {text:  , font: *awesome}
                      - string: {text:  , font: *awesome}
                      - string: {text:  , font: *awesome}
                      - string: {text:  , foreground: 00ff00ff, font: *awesome}
                - string: {text: "{capacity}%", left-margin: 8}
        content:
          map:
            conditions:
              state == unknown:
                <<: *discharging
              state == discharging:
                <<: *discharging
              state == charging:
                - string: {text:  , foreground: 00ff00ff, font: *awesome}
                - string: {text: "{capacity}%", left-margin: 8}
              state == full:
                - string: {text:  , foreground: 00ff00ff, font: *awesome}
                - string: {text: "{capacity}%", left-margin: 8} 

    - label:
        content:
          string:
            on-click: systemctl poweroff
            text: 
            right-margin: 7
            font: *awesome
